#!/bin/bash

function ctrl_c() {
	echo -e '\nExiting on SIGINT / Ctrl-C...'
	exit
}

# Catch SIGINT and exit
trap ctrl_c SIGINT

if [ -a /usr/bin/lua ]
	then
		while :
			do
			echo "(Re)starting Crackbot - Press Ctrl-C to break."
			lua init.lua
			done
	else
		echo "Lua was not found at /usr/bin/lua! If lua is installed in this computer, then you may safely proceed by running lua init.lua inside the directory wherein Crackbot resides."
fi
