AddOption('--32bit',dest="_32bit",action='store_true',default=True,help="32-bit platform target")
AddOption('--sse',dest="sse",action='store_true',default=False,help="Enable SSE optimisations")
AddOption('--sse2',dest="sse2",action='store_true',default=False,help="Enable SSE2 optimisations")
AddOption('--sse3',dest="sse3",action='store_true',default=False,help="Enable SSE3 optimisations")
AddOption('--sse4',dest="sse4",action='store_true',default=False,help="Enable SSE4 optimisations")
AddOption('--avx',dest="avx",action='store_true',default=False,help="Enable AVX optimisations")
AddOption('--avx2',dest="avx",action='store_true',default=False,help="Enable AVX2 optimisations")
AddOption('--win',dest="win",action='store_true',default=False,help="Windows platform target.")
AddOption('--lin',dest="lin",action='store_true',default=False,help="Linux platform target")
AddOption('--macosx',dest="macosx",action='store_true',default=False,help="Mac OS X platform target")
AddOption('--rpi',dest="rpi",action='store_true',default=False,help="Raspbain platform target")


if not GetOption('lin') and not GetOption('win') and not GetOption('rpi') and not GetOption('macosx'):
	print "You must specify a platform to target"
	raise SystemExit(1)

# if the platform is windows switch to a mingw toolset, use the default otherwise

#if GetOption('win'):
#	env = Environment(tools = ['mingw'], ENV = os.environ)
#else:
#	env = Environment(tools = ['default'], ENV = os.environ)

#env.Append(CFLAGS=['-pthread -llua5.1'])
#env.Append(LIBS=['pthread', 'lua'])


# check if we're compiling for macosx, if we are include macosx specific libraries and defines.

if GetOption('macosx'):
	env.Append(CFLAGS=['-I/Library/Frameworks/Lua.framework/Headers'])
	env.Append(LINKFLAGS=['-framework'])
	env.Append(LINKFLAGS=['Lua'])
# defines
# =======

# A lot of commandline flags translate directly into defines. those flags follow:
if GetOption('_32bit'):
	env.Append(CFlAGS=['-m32'])
	#env.Append(LINKFLAGS=['-m32'])

if GetOption('sse'):
	env.Append(CCFLAGS='-msse')
if GetOption('sse2'):
	env.Append(CFLAGS='-msse2')
if GetOption('sse3'):
	env.Append(CFLAGS='-msse3')
if GetOption('sse4'):
	env.Append(CFLAGS='-msse4')
if GetOption('avx'):
	env.Append(CFLAGS='-mavx')
if GetOption('avx2'):
	env.Append(CFLAGS='-maxv2')

# use some settings to detect what name to use for the executable
Name = "luasandbox"

if GetOption('macosx'):
	Name += "-x"

if GetOption('win'):
	Name += ".exe"

# set a default target
t=env.Program(target=Name, source=['code.c'])
Default(t)
